import { useEffect, useState } from 'react';
import snapshot from '../data/cpStatsSnapshot.json';
import { cppPracticeRepo } from '../data/resumeData';

// stats.json is regenerated by cpp_practice's update-stats workflow on every
// push, so fetching it straight from the raw CDN keeps this page current
// without redeploying the site. The bundled snapshot renders instantly and
// covers us if the fetch fails (offline, rate limit, repo renamed).
const STATS_URL = `https://raw.githubusercontent.com/${cppPracticeRepo}/main/stats.json`;

/**
 * @returns {{stats: object, status: 'loading'|'live'|'snapshot'}}
 *   `stats` is always usable; `status` reports where it came from.
 */
export default function useCpStats() {
  const [stats, setStats] = useState(snapshot);
  const [status, setStatus] = useState('loading');

  useEffect(() => {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 8000);

    fetch(STATS_URL, { signal: controller.signal, cache: 'no-cache' })
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        // Guard against a half-written or reshaped file rendering NaNs.
        if (!data?.totals?.problems) throw new Error('unexpected shape');
        setStats(data);
        setStatus('live');
      })
      .catch(() => setStatus('snapshot'))
      .finally(() => clearTimeout(timeout));

    return () => {
      clearTimeout(timeout);
      controller.abort();
    };
  }, []);

  return { stats, status };
}
